---
abstract: 'A simple Logger module recording db transactions in a SQLite db'
author:
  - 'Sholto Maud'
build_requires: {}
configure_requires:
  Module::Install
dynamic_config: 1
generated_by: 'Module::Install'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Galileo
no_index:
  file:
    - README.pod
provides:
  Logger:
    file: lib/Logger.pm
    version: 0.10
requires:
  DBI:SQLite
  JSON
  DateTime
  perl: v5.10.0
resources:
  bugtracker: http://github.com/shotlom/Logger/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/shotlom/Logger
version: 0.10